version: '3.7'
services:
  app:
    image: eugenci/papermerge:2.0.0
    container_name: papermerge_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - media_root:/opt/media
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
  db:
    image: postgres:12.3
    container_name: postgres_db
    volumes:
      - postgres_data7:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname
  redis:
    container_name: 'redis'
    image: 'redis:6'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redisdata:/data'
  worker:
    image: eugenci/papermerge-worker:v2.0.0
    container_name: papermerge_worker
    volumes:
      - media_root:/opt/media
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432      
volumes:
  postgres_data7:
  media_root:
  redisdata:
